# Generated by Django 4.1.2 on 2022-10-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_patient_road_map_user_bio_user_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='road_map',
            field=models.TextField(default='None set', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='Tx_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('session_chart', models.TextField(default='', max_length=250)),
                ('chart_patient_sees', models.TextField(default='', max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(default='', max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tx_session')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.therapist')),
            ],
        ),
        migrations.AddField(
            model_name='therapist',
            name='session',
            field=models.ManyToManyField(to='main_app.tx_session'),
        ),
    ]
