# Generated by Django 4.1.2 on 2022-10-23 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_patient_road_map_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_note',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='session_note',
            name='therapist',
        ),
        migrations.AddField(
            model_name='session_note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
